### PR TITLE
Added bindings to TextCtrl

### PR DESCRIPTION
**Pull request by Shallowmallow**
Added bindings to TextCtrl

### CODE REVIEW

**Comment by ianharrigan** [comment]
yikes! Thanks... lots of api gaps fill in there!

**Comment by Shallowmallow** [comment]
Most of them aren't really useful to haxeui, but it's always nice to have :)

Le lun. 9 janv. 2023 à 19:15, Ian Harrigan ***@***.***> a
écrit :

**Comment by ianharrigan** [comment]
https://github.com/haxeui/hxWidgets/actions/runs/3876536249/jobs/6610491098

Ill take a look

**Comment by ianharrigan** [comment]
https://github.com/haxeui/hxWidgets/commit/45972ae6086f8e5f50bc9e5cb9e9475117806cd0

```cpp
 ::Dynamic TextCtrl_obj::get_selection(){
            	HX_STACKFRAME(&_hx_pos_73cec53f5b87b09c_118_get_selection)
HXLINE( 119)		 long start = ( ( long)(0) );
HXLINE( 120)		 long end = ( ( long)(0) );
HXLINE( 121)		 long* startPtr = ::cpp::Pointer_obj::addressOf(start)->get_raw();
HXLINE( 122)		 long* endPtr = ::cpp::Pointer_obj::addressOf(end)->get_raw();
HXLINE( 124)		this->get_textCtrlRef()->ptr->GetSelection(startPtr,endPtr);
HXLINE( 125)		return  ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("start",62,74,0b,84),start)
            			->setFixed(1,HX_("end",db,03,4d,00),end));
            	}
```

I think the generated cpp looks alright, i could do without the casts, but i can live with it for now. Maybe some smart "abstract" stuff...

**Comment by Shallowmallow** [comment]
Nice work ! Good idea to have a long extern class . I am understanding
haxeui-widgets better and better but I have much yet to learn about C++ ;)

Le lun. 9 janv. 2023 à 20:24, Ian Harrigan ***@***.***> a
écrit :

**Comment by ianharrigan** [comment]
image

back in business :)

**Comment by Shallowmallow** [comment]
Bravo !! I'm sure you happy to have github actions haha.
The good side is that it seems that haxe did improve with versions ( at
least on Linux)


Le lun. 9 janv. 2023 à 22:04, Ian Harrigan ***@***.***> a
écrit :

**Comment by ianharrigan** [comment]
100%

**Pull request merged**
