### PR TITLE
Adding utf8 support to the TextCtrl widget

### PR DESCRIPTION
**Pull request by elnabo**

### CODE REVIEW

**Comment by ibilon** [comment]
Seems good,
what do you think @ianharrigan?

**Comment by ianharrigan** [comment]
Where is the `fromUtf8` defined? I cant find it, but probably being blind. Also, we sure we dont need the `.destroy` anymore? (though im not sure what `fromUtf8`returns so maybe no)

**Comment by ianharrigan** [comment]
Ah yes, i was being blind... :)

**Comment by ianharrigan** [comment]
Look good!

**Pull request merged**
